### ISSUE TITLE
Dockerfile/cloudbuild.yaml in subdirectory

### ISSUE THREAD

**Issue by sabrehagen** [GoogleCloudBuild/gcbapp-example#2]
Hi,

We have a number of Dockerfiles and cloudbuild.yamls in subfolders of our mono-repo and the GitHub cloudbuild check does not detect them. What can be done to remedy this?

For example:

services/api/cloudbuild.yaml
services/websocket/cloudbuild.yaml

![screenshot_20180812-153307_01](https://user-images.githubusercontent.com/1094600/44005676-3f86d91a-9e45-11e8-95b9-9f98a4ae7249.png)

**Comment by fikriauliya** [comment]
I encounter the same issue, did you find the solution? @sabrehagen

**Comment by sabrehagen** [comment]
@fikriauliya A solution was provided over [here](https://stackoverflow.com/questions/51861870/github-cloud-build-integration-with-multiple-cloudbuild-yamls-in-monorepo/52894592#52894592). It's a workaround, not a native solution.

**Comment by fikriauliya** [comment]
I have better solution:
1) In GCP dashboard, set `cloudbuild.yaml location` & `Included files filter (glob)` to your subproject:
<img width="432" alt="screen shot 2018-11-08 at 10 37 27" src="https://user-images.githubusercontent.com/341555/48176382-577da980-e342-11e8-88dc-de54e2ef58d9.png">

<img width="415" alt="screen shot 2018-11-08 at 10 38 07" src="https://user-images.githubusercontent.com/341555/48176411-73814b00-e342-11e8-8cd6-856be6cc3d74.png">

2) In `cloudbuild.yaml`, set `dir` to the subproject:
![screen shot 2018-11-08 at 10 40 09](https://user-images.githubusercontent.com/341555/48176465-b04d4200-e342-11e8-9ef0-718012c07380.png)

**Comment by whillas** [comment]
I have tried this and it keeps coming back with
```
unable to prepare context: unable to evaluate symlinks in Dockerfile path: lstat /workspace/servers/detctron2/Dockerfile: no such file or directory
```
And i'm certain that `servers/detctron2/Dockerfile` exisits in the git repo. Do i have to clone the repo as part of the build???
