### ISSUE TITLE
Possible to open source the github app source code?

### ISSUE THREAD

**Issue by ofpiyush** [GoogleCloudBuild/gcbapp-example#4]
We want to make a few changes to how the app integration works:

- Ignore submitting the build altogether if this file doesn't exist.
- Change the path of where the app looks for `cloudbuild.yaml` file, ignore the `Dockerfile`.
- Auto trigger builds on github tags as well.

We've been using the build triggers setup on GCB, but that requires a lot of setup for every repo. The app is perfect as we can have it enabled for our entire org and any developer that wants to use it can opt in by adding the `cloudbuild` file. (hence the ignore if file doesn't exist)

We understand that some, if not all these requirements might be pretty specific to how we want to use GCB.

If we had access to the source code, we'd modify and host a version of the github app ourselves.
That would solve all of our use cases and maybe other people's as well who want to make minor edits for their bespoke use cases.

**Comment by nof20** [comment]
Hey Piyush,

Glad you're finding this functionality helpful!  I don't think open source makes sense for us right now, but we do actually have some new functionality coming out into Alpha very soon which gives you all three of those things you mentioned.  If you're interested in joining the wait-list, email me (franklinn@google.com) so we can understand your use-cases in detail.

Nick

**Comment by ofpiyush** [comment]
Since people are landing on this, it's worth mentioning that after some back and forth their response was:

> We don't currently have this sort of global configuration of default App trigger handling on our roadmap and would direct users to create GCB triggers for this.

As GCB triggers also don't have org level setup, no dice for org level defaults and setup. 

They did mention

> Other users have written lightweight bridge services that receives GitHub webhooks directly and then handles the filtering logic and triggers builds via the API.
